name: Deploy to Server

on:
  push:
    branches:
      - main # Change to your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOST}} << 'EOF'
            cd /home/git/vigilant-dollop
            git pull origin main
            docker build -t your_image_name .
            docker run -d --name your_container_name -p 80:80 your_image_name
          EOF
