name: Deploy to Server

on:
  push:
    branches:
      - main # Change to your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Git Pull
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                  cd vigilant-dollop
                  git pull
                  

