name: Deploy to Server

on:
  push:
    branches:
      - main # Change to your default branch if not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0

        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git Pull
        run: |
          cd ${{ github.workspace }}
          ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ssh ${{secrets.USER}}@${{ secrets.HOST }} "cd /home/github/vigilant-dollop && git pull origin main"
          echo "Successfully pulled repo."

      - name: Docker build
        run: |
          cd ${{ github.workspace }}
          ssh ${{secrets.USER}}@${{ secrets.HOST }} "cd vigilant-dollop && docker build -t nextjs:latest -f Dockerfile ."
          ssh ${{secrets.USER}}@${{ secrets.HOST }} "docker build -t nginx:latest -f nginx/Dockerfile nginx"
      - name: Docker Compose pull and up
        run: |
          cd ${{ github.workspace }}
          ssh ${{secrets.USER}}@${{ secrets.HOST }} "cd vigilant-dollop && docker compose pull && docker compose up -d"
          echo "Successfully deployed app."
